name: "FinanTrack"
services:
  backend:
    container_name: finanzas-backend
    build: 
      context: /srv/dev-disk-by-uuid-668CD9B48CD97ECD/NAS/Cosas/OMV/proyectoSN/project-back
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URI: mysql+pymysql://root:root@192.168.1.177:33060/finanzas
    networks:
      - app_network
    volumes:
      - .:/app
  frontend:
    container_name: finanzas-frontend
    build:
      context: /srv/dev-disk-by-uuid-668CD9B48CD97ECD/NAS/Cosas/OMV/proyectoSN/project-front
    ports:
      - "80:80"

  mysql:
    container_name: mysql-db-finanzas
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    image: mysql
    volumes:
      - mysql-db-finanzas-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=192.168.1.177
      - PMA_PORT=33060

networks:
  app_network:
    driver: bridge

volumes:
  mysql-db-finanzas-data:
